version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_school_catalog
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
    container_name: backend_service
    restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin@mongodb:27017

  frontend:
    build:
      context: ./client
    container_name: frontend_service
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data: